### ISSUE TITLE
express에서 비동기 통신 사용

### ISSUE THREAD

**Issue by SkynI25** [YAPP13-4/semi-basement#36]
```javascript
app.get('/sc/test', (req, res) => {
    let result = [];
    SONG_URL_LIST.map((url) => {
        return axios.get(resolveUrl(url))
            .then(response => {
                result[0] = response.id;
            })
            .catch(err => {
               console.log(err);
            })
    })
    res.send(result);
});
```
에서 then 으로 넘어가지않고 catch로 넘어감

**Comment by SoYoung210** [comment]
@SkynI25  catch 문에 잡히는 에러로그 전체 올려주세요.

```jsx
app.get('/sc/test', (req, res) => {
    let result = [];
    SONG_URL_LIST.map((url) => {
        console.log('url',url); //이부분 
        return axios.get(resolveUrl(url))
            .then(response => {
                result[0] = response.id;
            })
            .catch(err => {
               console.log(err);
            })
    })
    res.send(result);
});
```

`console.log('url',url); //이부분 ` 잘 나오나요 ?

**Comment by SkynI25** [comment]
```
{ Error: Request failed with status code 404
    at createError (C:\Users\rlxo1\Documents\semi-basement\back\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\rlxo1\Documents\semi-basement\back\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\rlxo1\Documents\semi-basement\back\node_modules\axios\lib\adapters\http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     url: '//api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505',
     data: undefined },
  request:
   ClientRequest {
     domain: null,
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 287,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 49,
        [Symbol(bytesRead)]: 422 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 287,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 49,
        [Symbol(bytesRead)]: 422 },
     _header: 'GET //api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: localhost\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '//api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505',
        redirects: [],
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505' },
     [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { date: 'Sat, 22 Sep 2018 15:05:57 GMT',
        server: 'Apache',
        'x-frame-options': 'SAMEORIGIN',
        'content-length': '229',
        connection: 'close',
        'content-type': 'text/html; charset=iso-8859-1' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: '//api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET //api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: localhost\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '//api.soundcloud.com/resolve.json?url=https://soundcloud.com/amirarief/love-will-set-you-free-amirarief-kodaline-cover-mp3&client_id=a281614d7f34dc30b665dfcaa3ed7505',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /api.soundcloud.com/resolve.json was not found on this server.</p>\n</body></html>\n' } }
```

**Comment by SkynI25** [comment]
> @SkynI25 catch 문에 잡히는 에러로그 전체 올려주세요.
> 
> ```js-jsx
> app.get('/sc/test', (req, res) => {
>     let result = [];
>     SONG_URL_LIST.map((url) => {
>         console.log('url',url); //이부분 
>         return axios.get(resolveUrl(url))
>             .then(response => {
>                 result[0] = response.id;
>             })
>             .catch(err => {
>                console.log(err);
>             })
>     })
>     res.send(result);
> });
> ```
> 
> `console.log('url',url); //이부분` 잘 나오나요 ?

네 잘 나와요!
